apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 5
  # behavior:
  #   scaleDown:
  #     policies:
  #     - type: Pods
  #       value: 4
  #       periodSeconds: 60
  #     - type: Percent
  #       value: 10
  #       periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # targetCPUUtilizationPercentage: 30