apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals:
  - password=bXBYbS43qF
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
  - wordpress-deployment.yaml
  - ingress.yaml
  - horizontal-pod-autoscaler.yaml


# Create secret kubectl or use kms